#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'sensing_report'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 35

# The Active Message type associated with this message.
AM_TYPE = -1

class Sensing(tinyos.message.Message.Message):
    # Create a new Sensing of size 35.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=35):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <Sensing> \n"
        try:
            s += "  [seqno=%u]\n" % (self.get_seqno())
        except:
            pass
        try:
            s += "  [sender=%u]\n" % (self.get_sender())
        except:
            pass
        try:
            s += "  [voltage=%u]\n" % (self.get_voltage())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: seqno
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'seqno' is signed (False).
    #
    def isSigned_seqno(self):
        return False
    
    #
    # Return whether the field 'seqno' is an array (False).
    #
    def isArray_seqno(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'seqno'
    #
    def offset_seqno(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'seqno'
    #
    def offsetBits_seqno(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'seqno'
    #
    def get_seqno(self):
        return self.getUIntElement(self.offsetBits_seqno(), 16, 1)
    
    #
    # Set the value of the field 'seqno'
    #
    def set_seqno(self, value):
        self.setUIntElement(self.offsetBits_seqno(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'seqno'
    #
    def size_seqno(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'seqno'
    #
    def sizeBits_seqno(self):
        return 16
    
    #
    # Accessor methods for field: sender
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'sender' is signed (False).
    #
    def isSigned_sender(self):
        return False
    
    #
    # Return whether the field 'sender' is an array (False).
    #
    def isArray_sender(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sender'
    #
    def offset_sender(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'sender'
    #
    def offsetBits_sender(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'sender'
    #
    def get_sender(self):
        return self.getUIntElement(self.offsetBits_sender(), 16, 1)
    
    #
    # Set the value of the field 'sender'
    #
    def set_sender(self, value):
        self.setUIntElement(self.offsetBits_sender(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'sender'
    #
    def size_sender(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'sender'
    #
    def sizeBits_sender(self):
        return 16
    
    #
    # Accessor methods for field: voltage
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'voltage' is signed (False).
    #
    def isSigned_voltage(self):
        return False
    
    #
    # Return whether the field 'voltage' is an array (False).
    #
    def isArray_voltage(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'voltage'
    #
    def offset_voltage(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'voltage'
    #
    def offsetBits_voltage(self):
        return 32
    
    #
    # Return the value (as a short) of the field 'voltage'
    #
    def get_voltage(self):
        return self.getUIntElement(self.offsetBits_voltage(), 16, 1)
    
    #
    # Set the value of the field 'voltage'
    #
    def set_voltage(self, value):
        self.setUIntElement(self.offsetBits_voltage(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'voltage'
    #
    def size_voltage(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'voltage'
    #
    def sizeBits_voltage(self):
        return 16
    
